### ISSUE TITLE
Pre release cards are stored by name not card_id. 

### ISSUE THREAD

**Issue by Ekkstein** [schmich/hearthstone-card-images#1]
Hey Chris!

We started using your card images and are hoping to be able to load the pre-card_images soon.
They are still stored via card_name and it would be helpful (consistent) if they also would be stored with their card_id. 
I don't mean to be pushy and you probably will get to it asap, I just wanted to know if and when you intend to update them. 
Thank you very much for your initiative with the card images. We appreciate it.
Also, if I can help you doing it, let me know.

Hearthy Greetings!
Ekard

**Comment by schmich** [comment]
Well met, Ekard! Sorry for the delay, but the released Un'Goro cards should be accessible via card ID now. If it works well for you, you can close this issue.

Also, out of curiosity, what's your project that you're using these card images for? I like to have an idea of how/where this is used.

**Comment by Ekkstein** [comment]
First of all, thank you very much for the quick response.
We are building pitytracker.com and hearthstonemetadecks.com albeit, we are not using the git cdn yet. At this point we are loading the images from the repo and serve them from our own server.
I just loaded the images using the card_ids provided by hearthstonejson.com and it all worked as intended.
