### ISSUE TITLE
Boomsday Project Cards

### ISSUE THREAD

**Issue by jrattray13** [schmich/hearthstone-card-images#10]
Hi, do you plan on adding the released Boomsday cards?

If not could you perhaps comment how you acquire the images so I can do it myself?

Thanks

**Comment by schmich** [comment]
Published as version 4.9.0.

Sorry for the delay. I had the changes sitting around but kept getting distracted before being able to publish them.

**Comment by jrattray13** [comment]
Awesome thanks for swift response, appreciated!
