### ISSUE TITLE
Different card sizes

### ISSUE THREAD

**Issue by mhaubenwallner** [schmich/hearthstone-card-images#12]
Hello,

I found out that most cards have the same size, but some are different. 
Do you have any control over this or do I have to resize them manually to fit the other cards?

If it has to be done manually I can provide you a pull request when I'm done resizing them - I just need to know :)

Here is the list:
North Sea Kraken - 2520.png
Spiteful Smith - 61.png
Angry Chicken - 1688.png
Coldlight Oracle - 1016.png
Mountain Giant - 993.png
Ice Block - 192.png
Tauren Warrior - 45.png
Amani Berserker - 790.png
Raging Worgen - 1155.png
Molten Giant - 1372.png
Ghostly Charger - 47051.png
Witchwood Piper - 47142.png
Witchwood Grizzly - 47346.png
Warbot - 2019.png
Shadowboxer - 2040.png
Prince Malchezaar - 39840.png
Jungle Moonkin - 2923.png
Ixlid, Fungal Lord - 45859.png
Marin the Fox - 45988.png
Aberrant Berserker - 38531.png
Bloodhoof Brave - 38738.png
Living Mana - 41094.png

Thanks,
Mario

**Comment by schmich** [comment]
They should be fixed now. Thanks!
