### ISSUE TITLE
Cards in other languages

### ISSUE THREAD

**Issue by mhaubenwallner** [schmich/hearthstone-card-images#16]
Hey there,

is there some sort of limitation besides Github repo size (issue #5) that would block you from releasing cards in other languages?

If I can support you somehow with this task I would gladly help :)

Thanks so far,
Mario

**Comment by schmich** [comment]
This project is now using the [official Hearthstone API](https://develop.battle.net/documentation/api-reference/hearthstone-game-data-api) for card images which are offered in all Hearthstone locales, so this repo now has card images for the following locales:

- de_DE
- en_US
- es_ES
- es_MX
- fr_FR
- it_IT
- ja_JP
- ko_KR
- pl_PL
- pt_BR
- ru_RU
- th_TH
- zh_CN
- zh_TW

The locale is part of the card image URL, e.g. https://raw.githubusercontent.com/schmich/hearthstone-card-images/master/cards/en_US/53551.png.
