### ISSUE TITLE
Images are small, How to resize to the resolution?

### ISSUE THREAD

**Issue by jhzao82** [schmich/hearthstone-card-images#21]
Image looks good, how to get those resolution?

**Comment by jhzao82** [comment]
What about this repo? why others want use it?
It's looks like a generator of cards, but cards already exists in this repo.

**Comment by sebastientromp** [comment]
This repo is not the card generator, but a storage for card images. 
I don't know what generator is used to created the images though

**Comment by sebastientromp** [comment]
THat said, I myself would very much like to have the image in high-res, as well as a golden version, if at all possible.

**Comment by schmich** [comment]
This project has migrated to use the [official Hearthstone API](https://develop.battle.net/documentation/api-reference/hearthstone-game-data-api) which offers much higher resolution card images than before ([example](https://raw.githubusercontent.com/schmich/hearthstone-card-images/master/cards/en_US/53551.png)). This is the max resolution.

For golden cards, I can only point you to another card image source like [Hearthpwn](https://www.hearthpwn.com/cards/90145-shirvallah-the-tiger). This is being tracked here by #5, and if Blizzard offers golden card images, I will happily integrate them into this repo.
