### ISSUE TITLE
Dalaran Heist  patch 14.2.0.30795 has been released

### ISSUE THREAD

**Issue by sebastientromp** [schmich/hearthstone-card-images#22]
As you're probably aware of :)

Do you know if adding the new cards is something you plan to do soon? I'm considering moving to an alternate source (like downloading the art from hearthstonejson.com) instead. Do you think I should wait until a new release is done?

Cheers,

Seb

**Comment by schmich** [comment]
My apologies on this. I've moved this project over to use the [official Hearthstone API](https://develop.battle.net/documentation/api-reference/hearthstone-game-data-api) for images, so keeping cards up-to-date will be _significantly_ easier moving forward. This project is now pretty redundant with what Blizzard themselves offer, but I will keep it going.

I've updated the card images up through the latest Saviors of Uldum release.
