### ISSUE TITLE
Add npm support

### ISSUE THREAD

**Issue by Soviut** [schmich/hearthstone-card-images#4]
It would be nice to be able to install this via npm

**Comment by schmich** [comment]
Fixed. See https://www.npmjs.com/package/hearthstone-card-images

`npm install --save hearthstone-card-images`

```js
const images = require('hearthstone-card-images');

for (const card of images) {
  console.log(`${card.id} -> ${card.url}`);
}
```

The NPM package will be updated when cards are added and art is updated.
