### ISSUE TITLE
How to use `create_images.rb`?

### ISSUE THREAD

**Issue by martin-eden** [schmich/hearthstone-card-images#7]
Hello,

I wish to run `create-images.rb` file. 

I'm doing
```
$ ruby create-images.rb
```
and getting
```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- progress_bar (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from create-images.rb:2:in `<main>'
```

What is wrong? 

Ruby version: `ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]`

**Comment by martin-eden** [comment]
Well, I just wished to try some ruby.

Regarding images, I've got them by `git clone`. (Which somewhy don't mentioned in readme. Also there is `curl | bash` method which probably will be blamed as dangerous.)

**Comment by schmich** [comment]
Sure! The `progress_bar` is just an external library dependency. Typically, in a Ruby app, there would be a `Gemfile` (kind of like JavaScript's `package.json`) that would specify the dependency, but I skipped that for this project.

If you want to run `create-images.rb` yourself, try this:

```
gem install progress_bar
ruby create-images.rb
```

Good call on the `git clone` method. I'll add that.

**Comment by schmich** [comment]
I just pushed an update to remove the jq dependency.

**Comment by martin-eden** [comment]
Thank you!

**Comment by martin-eden** [comment]
I created bash/Lua scripts to fetch card images and rename them. Shared results in [hearthstone_cards_named ](https://github.com/martin-eden/hearthstone_cards_named) repository.

**Comment by schmich** [comment]
Nice! That's a good way to browse the cards. I can't wait until HS has 70+ expansions like MTG, haha...

**Comment by martin-eden** [comment]
Shared today my [code to rename cards](https://github.com/martin-eden/hearthstone_cards_renamer). (In case you'll wish to tinker with Lua.)
