### ISSUE TITLE
Weapon: Attack/Durability without numbers

### ISSUE THREAD

**Issue by haubix** [schmich/hearthstone-card-images#9]
Hi there and thanks for your awesome service!

Is there a possibility to get a weapon without attack and durability numbers? 
I just need it for an overlay but I cannot find a proper picture anywhere.

Is there a possibility that you can generate one for me?

Thanks in advance!

**Comment by schmich** [comment]
I don't have the ability to do that, but you should check out [hearthcards.net](http://hearthcards.net/) or [Sunwell](https://github.com/HearthSim/Sunwell) where the components are separated.

- http://hearthcards.net/card_js_templates/card_weapon_neutral.png
- http://hearthcards.net/card_js_templates/card_weapon_warrior.png
- http://hearthcards.net/card_js_templates/card_weapon_shaman.png
- http://hearthcards.net/card_js_templates/card_weapon_rogue.png
- http://hearthcards.net/card_js_templates/card_weapon_paladin.png
- http://hearthcards.net/card_js_templates/card_weapon_hunter.png
- http://hearthcards.net/card_js_templates/card_weapon_druid.png
- http://hearthcards.net/card_js_templates/card_weapon_warlock.png
- http://hearthcards.net/card_js_templates/card_weapon_mage.png
- http://hearthcards.net/card_js_templates/card_weapon_priest.png

**Comment by haubix** [comment]
Thank you :)
